const henkel_products = [
  {
    id: 1,
    name: "Syoss Full Hair 5 šampon za tanku i spljoštenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Fullhair5_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 2,
    name: "Syoss Blonde&Silver ljubičasti šampon za plavu i sijedu kosu ",
    img: "https://cdn.notinoimg.com/detail_zoom/syoss/9000101290097_01-o/syoss-blonde-silver-ljubicasti-sampon-za-plavu-i-sijedu-kosu___230522.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: true
    }
  },
  {
    id: 3,
    name: "Syoss Salonplex šampon za oštećenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Salonplex_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 4,
    name: "Syoss Volume šampon za tanku kosu bez volumena",
    img: "https://cdn.notinoimg.com/detail_main_mq/syoss/9000101277296_01-o/syoss-volume-sampon-za-tanku-kosu-bez-volumena___230522.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 5,
    name: "Syoss Color šampon posebno razvijen za obojenu ili posvijetljenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Color_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 6.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 6,
    name: "Syoss Balancing šampon za normalnu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/syoss-hr_balancing-shampoo_normal-hair_packshot_573x1440?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 3.5,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 7,
    name: "Syoss Anti-Dandruff šampon za kosu sklonu peruti",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Anti-Dandruff_shampoo-951x2482?wid=240&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: true,
      grayHair: false
    }
  },
  {
    id: 8,
    name: "Syoss Repair šampon za oštećenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Repair_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 9,
    name: "Syoss Keratin šampon za slabu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/5201143725606_30270820_SY_Keratin-RL20_SHP_750_PLEELVLTROBGALCZSKHUSIHRBIHMNESRBMKUA_2810793_front?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 10,
    name: "Syoss Pure Volume micelarni šampon",
    img: "https://dm.henkel-dam.com/is/image/henkel/syoss-hr_pure-volume-shampoo_normal-hair_packshot_430x1080?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: true,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 11,
    name: "Syoss Oleo Intense šampon za sjajnu i mekanu kosu",
    img: "https://licilasicdn.s3.amazonaws.com/public/product_images/47779/gallery/original/949495238.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 12,
    name: "Syoss Intense Plex šampon za veoma oštećenu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/syoss/9000101731460_01-o/syoss-intense-plex-sampon-za-veoma-ostecenu-kosu___231222.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 13,
    name: "Syoss Men Volume šampon za tanku i spljoštenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Salonplex_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 14,
    name: "Syoss Men Clean&Cool šampon za masnu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_MEN_CleanCool_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "M",
    scalpType: {
      veryDry: false,
      dryToNormal: false,
      normal: false,
      normalToGreasy: true,
      veryGreasy: true
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 15,
    name: "Syoss Men Power šampon za normalnu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/9000101681062_30270830_SY_MEN-Power-RL20_SHP_750_PLEELVLTROBGALCZSKHUSIHRBIHMNESRBMKUA_2810794_front?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 16,
    name: "Gliss Oil Nutritive hranjivi šampon s uljem",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000100549837_01-o/schwarzkopf-gliss-oil-nutritive-hranjivi-sampon-s-uljem___240111.jpg",
    brand: "Gliss",
    price: 4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 17,
    name: "Gliss Ultimate Repair šampon za učvršćivanje za suhu i oštećenu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000100801416_01-o/schwarzkopf-gliss-ultimate-repair-sampon-za-ucvrscivanje-za-suhu-i-ostecenu-kosu___240111.jpg",
    brand: "Gliss",
    price: 3.2,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 18,
    name: "Gliss Supreme Length zaštitni šampon za dugu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101201147_01-o/schwarzkopf-gliss-supreme-length-zastitni-sampon-za-dugu-kosu___240111.jpg",
    brand: "Gliss",
    price: 4,
    gender: "F",
    scalpType: null,
    hairLength: {
      short: false,
      medium: false,
      long: true
    },
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 19,
    name: "Gliss Aqua Revive šampon za normalnu i suhu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101659092_01-o/schwarzkopf-gliss-aqua-revive-sampon-za-normalnu-i-suhu-kosu___240111.jpg",
    brand: "Gliss",
    price: 3.2,
    gender: "F",
    scalpType: {
      veryDry: true,
      dryToNormal: true,
      normal: true,
      normalToGreasy: false,
      veryGreasy: false
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 20,
    name: "Gliss Total Repair šampon za intenzivnu regeneraciju",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000100549493_01-o/schwarzkopf-gliss-total-repair-sampon-za-intenzivnu-regeneraciju___240111.jpg",
    brand: "Gliss",
    price: 4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: true,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 21,
    name: "Gliss Color Perfector zaštitni šampon za obojenu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/4015000195324_01-o/schwarzkopf-gliss-color-perfector-zastitni-sampon-za-obojenu-kosu___240111.jpg",
    brand: "Gliss",
    price: 3.2,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: true,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 22,
    name: "Gliss Split Ends Miracle regenerirajući šampon za ispucale vrhove kose",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101287431_01-o/schwarzkopf-gliss-split-ends-miracle-regenerirajuci-sampon-za-ispucale-vrhove-kose___240111.jpg",
    brand: "Gliss",
    price: 4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: true,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 23,
    name: "Gliss Blonde Hair Perfector",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101617481_01-o/schwarzkopf-gliss-blonde-hair-perfector___240111.jpg",
    brand: "Gliss",
    price: 4.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 24,
    name: "Schauma 7 Herbs biljni šampon za normalnu i masnu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/3838824086750_01-o/schwarzkopf-schauma-7-herbs-biljni-sampon-za-normalnu-i-masnu-kosu___231101.jpg",
    brand: "Schauma",
    price: 4.5,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: false,
      normal: true,
      normalToGreasy: true,
      veryGreasy: true
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 25,
    name: "Schauma Fresh Matcha detoksikacijski šampon za čišćenje za masno vlasište i suhe vrhove",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101249743_01-o/schwarzkopf-schauma-fresh-matcha-detoksikacijski-sampon-za-ciscenje-za-masno-vlasiste-i-suhe-vrhove___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: false,
      normal: false,
      normalToGreasy: true,
      veryGreasy: false
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 26,
    name: "Schauma Q10 Fullness Šampon za tanku i rijetku kosu s koenzimom",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/3838824193106_01-o/schwarzkopf-schauma-q10-fullness-sampon-za-tanku-i-rijetku-kosu-s-koenzimom-q10___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 27,
    name: "Schauma Silver Reflex Šampon za neutraliziranje bakrenih tonova za posvijetljenu, hladno plavu kosu s pramenovima",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101259162_01-o/schwarzkopf-schauma-silver-reflex-sampon-za-neutraliziranje-bakrenih-tonova-za-posvijetljenu-hladno-plavu-kosu-s-pramenovima___231101.jpg",
    brand: "Schauma",
    price: 4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: true,
      normalHair: true,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 28,
    name: "Schauma Fresh it up! Osvježavajući šampon za masno vlasište i suhe vrhove, ",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/3838824293813_01-o/schwarzkopf-schauma-fresh-it-up-osvjezavajuci-sampon-za-masno-vlasiste-i-suhe-vrhove___231204.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: false,
      normal: false,
      normalToGreasy: true,
      veryGreasy: true
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 29,
    name: "Schauma Everyday Care Šampon za svakodnevno pranje kose s kamilicom",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101627428_01-o/schwarzkopf-schauma-everyday-care-sampon-za-svakodnevno-pranje-kose-s-kamilicom___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: {
      once: false,
      twoToThree: false,
      threeToFive: true,
      everyDay: true
    },
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 30,
    name: "Schauma Color Shine Šampon za obojenu i kosu s pramenovima",
    img: "https://media.dm-static.com/images/f_auto,q_auto,c_fit,h_440,w_500/v1700029004/products/pim/3838824086736-176653909/schauma-color-shine-sampon-za-obojenu-kosu-ili-kosu-s-pramenovima",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 31,
    name: "Schauma Argan Oil & Repair Obnavljajući šampon za suhu i oštećenu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101653045_01-o/schwarzkopf-schauma-argan-oil-repair-obnavljajuci-sampon-za-suhu-i-ostecenu-kosu___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: true,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 32,
    name: "Schauma Herbs & Volume Šampon za tanku kosu bez volumena",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101647433_01-o/schwarzkopf-schauma-herbs-volume-sampon-za-tanku-kosu-bez-volumena___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: false,
      normal: false,
      normalToGreasy: true,
      veryGreasy: true
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: {
      once: false,
      twoToThree: false,
      threeToFive: true,
      everyDay: true
    },
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 33,
    name: "Schauma Moisture & Shine Hidratantni šampon za normalnu i suhu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101704976_01-o/schwarzkopf-schauma-moisture-shine-hidratantni-sampon-za-normalnu-i-suhu-kosu___231101.jpg",
    brand: "Schauma",
    price: 2.6,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: true,
      normal: true,
      normalToGreasy: false,
      veryGreasy: false
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: {
      once: true,
      twoToThree: true,
      threeToFive: false,
      everyDay: false
    },
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: true,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 34,
    name: "Schauma Gentle Repair Nježan njegujući šampon za suhu i oštećenu kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101620825_01-o/schwarzkopf-schauma-gentle-repair-njezan-njegujuci-sampon-za-suhu-i-ostecenu-kosu___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: {
      veryDry: false,
      dryToNormal: true,
      normal: true,
      normalToGreasy: true,
      veryGreasy: false
    },
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: {
      once: false,
      twoToThree: true,
      threeToFive: true,
      everyDay: false
    },
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: true,
      thickHair: true,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: true,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 35,
    name: "Schauma Power Volume Šampon za volumen za nježnu i tanku kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000100952330_01-o/schwarzkopf-schauma-power-volume-sampon-za-volumen-za-njeznu-i-tanku-kosu___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThanSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 36,
    name: "Schauma MEN šampon za muškarce za svakodnevnu uporabu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/3838824086675_01-o/schwarzkopf-schauma-men-sampon-za-muskarce-za-svakodnevnu-uporabu___231101.jpg",
    brand: "Schauma",
    price: 2.6,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: {
      once: false,
      twoToThree: false,
      threeToFive: true,
      everyDay: true
    },
    hairTypeCharacteristics: null
  },
  {
    id: 37,
    name: "Schauma MEN šampon protiv peruti s đumbirom",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/3838824208985_01-o/schwarzkopf-schauma-men-sampon-protiv-peruti-s-umbirom___231101.jpg",
    brand: "Schauma",
    price: 4,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThanSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: false,
      containsDandruff: true,
      grayHair: false
    }
  },
  {
    id: 38,
    name: "Schauma MEN Osvježavajući šampon za lice, tijelo i kosu",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000101284799_01-o/schwarzkopf-schauma-men-osvjezavajuci-sampon-za-lice-tijelo-i-kosu___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: null
  },
  {
    id: 39,
    name: "Schauma MEN Gel za tuširanje i šampon 2 u 1 za muškarce",
    img: "https://cdn.notinoimg.com/detail_main_mq/schwarzkopf/9000100860246_01-o/schwarzkopf-schauma-men-gel-za-tusiranje-i-sampon-2-u-1-za-muskarce___231101.jpg",
    brand: "Schauma",
    price: 2.8,
    gender: "M",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: null
  },
  {
    id: 40,
    name: "Syoss Curls&Waves šampon za kovrčavu kosu ",
    img: "https://cdn.notinoimg.com/detail_main_mq/syoss/9000101277517_01-o/syoss-curls-waves-sampon-za-kovrcavu-i-valovitu-kosu___230522.jpg",
    brand: "Syoss",
    price: 4.1,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: {
      straight: false,
      wavy: true,
      curly: true
    },
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: null
  }
];

export default henkel_products;
