const henkel_products = [
  {
    id: 1,
    name: "Syoss Full Hair 5 šampon za tanku i spljoštenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Fullhair5_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThenSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 2,
    name: "Syoss Blonde&Silver ljubičasti šampon za plavu i sijedu kosu ",
    img: "https://cdn.notinoimg.com/detail_zoom/syoss/9000101290097_01-o/syoss-blonde-silver-ljubicasti-sampon-za-plavu-i-sijedu-kosu___230522.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: true
    }
  },
  {
    id: 3,
    name: "Syoss Salonplex šampon za oštećenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Salonplex_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThenSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 4,
    name: "Syoss Volume šampon za tanku kosu bez volumena",
    img: "https://cdn.notinoimg.com/detail_main_mq/syoss/9000101277296_01-o/syoss-volume-sampon-za-tanku-kosu-bez-volumena___230522.jpg",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: true,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 5,
    name: "Syoss Color šampon posebno je razvijen za obojenu ili posvijetljenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Color_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 6.8,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: false,
      dyedWithStoreBoughtDyes: true,
      professionallyDyedInSalon: true,
      selfBleached: true,
      professionallyBleachedInSalon: true
    },
    hairTreatmentFrequency: {
      never: false,
      oneToThreeTimes: true,
      threeToSixTimes: true,
      moreThenSixTimes: true
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: true,
      blondeHair: true,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 6,
    name: "Syoss Balancing šampon za normalnu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/syoss-hr_balancing-shampoo_normal-hair_packshot_573x1440?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 3.5,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: {
      neverDyed: true,
      dyedWithStoreBoughtDyes: false,
      professionallyDyedInSalon: false,
      selfBleached: false,
      professionallyBleachedInSalon: false
    },
    hairTreatmentFrequency: {
      never: true,
      oneToThreeTimes: false,
      threeToSixTimes: false,
      moreThenSixTimes: false
    },
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: true,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: true,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 7,
    name: "Syoss Anti-Dandruff šampon za kosu sklonu peruti",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Anti-Dandruff_shampoo-951x2482?wid=240&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: false,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: false,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: true,
      grayHair: false
    }
  },
  {
    id: 8,
    name: "Syoss Repair šampon za oštećenu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/Syoss_SHP_440_Repair_shampoo-951x2482?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: true,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: false,
      thinAndWeakHair: true,
      strawHair: true,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  },
  {
    id: 9,
    name: "Syoss Keratin šampon za slabu kosu",
    img: "https://dm.henkel-dam.com/is/image/henkel/5201143725606_30270820_SY_Keratin-RL20_SHP_750_PLEELVLTROBGALCZSKHUSIHRBIHMNESRBMKUA_2810793_front?wid=480&fmt=webp-alpha&qlt=90&fit=hfit",
    brand: "Syoss",
    price: 4.4,
    gender: "F",
    scalpType: null,
    hairLength: null,
    hairTexture: null,
    hairTreatment: null,
    hairTreatmentFrequency: null,
    hairWashFrequency: null,
    hairTypeCharacteristics: {
      damagedAndDriedEnds: false,
      proneToSplitEnds: true,
      greasyHair: false,
      thickHair: false,
      thinHair: true,
      thinAndWeakHair: true,
      strawHair: false,
      coloredHair: false,
      blondeHair: false,
      normalHair: false,
      withoutVolume: false,
      containsDandruff: false,
      grayHair: false
    }
  }
];

export default henkel_products;
